version: '3.9'
services:
  db: 
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localUser
      POSTGRES_PASSWORD: localPass
      POSTGRES_DB: localDb
  db-service:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
volumes:  
  postgres_data:
